### ISSUE TITLE
Update to new orbitdb version

### ISSUE THREAD

**Issue by oed** [3box/3box-pinning-node#140]
This should be quite simple I think since we are only opening DBs by their addresses.

Make sure IPFS works with S3.

**Comment by zachferland** [comment]
Ran with updates for orbit, also double checked ipfs changes. Looks good, but will have further finalize once we have a set orbit version and then can run everything as part of normal testing. Going to close now, since no initial changes to meet current stuff, but will still have pull in all stuff, orbit versions and our identity providers (did resolvers, etc). But that will all be tested are part of 3id/threadsV2 deployment.
