### ISSUE TITLE
Implement serverless function for getThread

### ISSUE THREAD

**Issue by oed** [3box/3box-pinning-node#147]
The serverless function uses the ipfs-s3 and orbitdb-redis stores to get the raw data from a users profile.

**Comment by michaelsena** [comment]
@zachferland can we move this back to backlog for next sprint?

**Comment by zachferland** [comment]
Yeah, moving, just wanted to put into 'saved' state for later 

Implementation Notes 

Extend thread AC to consume a log instance instead of orbitdb. And all write/update functions are not needed. Can get AC db log just by using the same general db read function already created. Once AC instantiated, just have single update for it to build capabilities lists. Then it can be passed to thread instance and thread can also be opened with the existing general db read function. 

Current state: only experimental, no complete implementation yet
