### ISSUE TITLE
Testing for multi-node write network

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-pinning-node#211]
- [ ] Dev env testing
- [ ] Integration testing

**Comment by zachferland** [comment]
Another bug to resolve, something seems out of order about when it decides to write heads to cache. A few times was able to have prior entry overwrite new entry. And looked like they could be differentiate by clock (not equivalent) but have to test sort function for sure.

To recreate, open dbA in one client on pinning1, sync, add new entry, then open dbA in second client on pinning2, pinning2 would overwrite latest entry/head with one prior to new entry.

**Comment by zachferland** [comment]
Actually looks a bit similar to https://github.com/orbitdb/orbit-db/pull/683 fix, but in ipfs log.

Basically _remoteHeads in orbitdb cache is writing value this.oplog.heads after getting heads from remote peer, but sometimes before its done loading and building log from its existing remoteHeads/localHeads. In this case a latest head can be lost, if current cache value is latest, getting overwritten by older remote value.

A naive fix it just to rewrite after ready, if not ready in original write. But maybe a better overall fix (now with this causing issue in multiple places) will be to improve how these states are managed, don't consume/exchange peer heads/data until that client is fully ready/loaded (log) instead of now where it does it right away.

**Comment by zachferland** [comment]
Bug resolved by 

https://github.com/3box/3box-pinning-node/pull/218
