### ISSUE TITLE
Q: Will this work in the browser via pubsub?

### ISSUE THREAD

**Issue by aphelionz** [3box/3box-pinning-node#302]
Would love to know :)

**Comment by oed** [comment]
Can you clarify your question a bit? Are you wondering if the code in this repo would run in a browser, or if it would communicate with a node that's in a browser using pubsub?

**Comment by aphelionz** [comment]
The former, I know it would likely be of limited utility but I'm still curious

**Comment by oed** [comment]
I think not out of the box since there are a few environment variables being set. Might be other things as well. Also note that there is no way for other nodes to explicitly connect to another node in the browser. You will need to connect using a websocket-star service or similar which tend to be slow.

**Comment by aphelionz** [comment]
Cool, thank you!
